apiVersion: v2
name: evellama
version: 0.1.1
description: A Helm chart for Kubernetes
type: application
home: https://evellama.io
sources:
  - https://github.com/evellama/evellama
dependencies: []
maintainers:
  - name: bokoboshahni
    email: shahni@bokobo.space
appVersion: "0.1.0"
